fd1-63-2018/fd1

yuliya1/home/9.04/index.html
yuliya1/home/9.04/style.css

@antonkulakov-it Please, review

Home work 9-04

---

index.css
index.html

homeWork 9.04

---

dima1745/work/9.04/forindex.css
dima1745/work/9.04/index.html

First Try.9.09

---

hannashyshko/home/9.04/index.css
hannashyshko/home/9.04/index.html

created basic structure of form

---

dmitrylunkov/home/9.04/index.html
dmitrylunkov/home/9.04/main.css

Homework from 9.04

---

ekaterinazhuk/home/9.04/index.html
ekaterinazhuk/home/9.04/main.css

homeWork-9-04-firstForm

---

vladdd/home/09.04/index2.css
vladdd/home/09.04/index2.html

Домашнее дз 09.04

---

sotickmars/home/9.04/CSS.css
sotickmars/home/9.04/index.html

home 9.04 \m/

---

oxana1510/home/9.04/index.html
oxana1510/home/9.04/stylesheet.css

Oxana1510 home 9.04

---

Marat/home/9.04/index.html
Marat/home/9.04/main.css

M home 9.04

---

hannashyshko/home/9.04/index.css

changed file

---

dmitrylunkov/work/11.04/index.html
dmitrylunkov/work/11.04/styles.css

work from 11.04 at IT Academy

---

oxana1510/home/11.04/index.html
oxana1510/home/11.04/style.css
oxana1510/work/11.04/file.css
oxana1510/work/11.04/index.html

11.04 home

---

dima1745/home/11.04/forindex.css
dima1745/home/11.04/index.html
dima1745/work/11.04/index.html
dima1745/work/11.04/indexfor.css

Zaharevich2home114

---

yuliya1/home/11.04/index.html
yuliya1/home/11.04/style.css

@antonkulakov-it  Please,review

Home work chess

---

medrom4/home/11.04/index.html
medrom4/home/11.04/index2.html
medrom4/home/11.04/stylecss.css
medrom4/home/11.04/stylecss2.css

какой из вариантов подходит больше?

два варианта создания доски

---

dmitrylunkov/home/11.04/index.html
dmitrylunkov/home/11.04/styles.css

Homework 11.04 checkers board. CSS gradients

---

fotenya/home/11.04/index.html
fotenya/home/11.04/main.css

home chess

---

Marat/home/11.04/index.html
Marat/home/11.04/main.css

home-11.04

---

ekaterinazhuk/home/index.html
ekaterinazhuk/home/main.css

firstDoska

---

vladdd/home/12.04/index12-04.html
vladdd/home/12.04/mycss11-04.css

home 11/04

---

knightjuly/home/11.04/index.html
knightjuly/home/11.04/main.css

home 13.04 2.07

---

vladdd/work/13.04/width/index.html

work 13/04

---

yuliya1/work/13.04/width/index.html
yuliya1/work/13.04/width/style.css

@antonkulakov-it Please review

Work 13.04 - Width

---

oxana1510/work/13.04/index.html
oxana1510/work/13.04/style.css

work 13.04

---

dmitrylunkov/work/13.04/index.html
dmitrylunkov/work/13.04/styles.css

Class work 13.04

---

medrom4/work/13.04/html.html
medrom4/work/13.04/style.css

work-13.04

---

Marat/work/13.04/index.html
Marat/work/13.04/style.css

Marat work 13.04

---

dmitrylunkov/work/14.04/index.html
dmitrylunkov/work/14.04/styles.css

Classwork 14.04

---

vladdd/work/14.04/index14-04.html
vladdd/work/14.04/mycss14-04.css

work 14.04

---

Tanivetka/work/13.04/index.css
Tanivetka/work/13.04/index.html

рабочка 13.04

---

Tanivetka/work/11.04/gradient.css
Tanivetka/work/11.04/gradient.html

рабочка 11.04

---

Tanivetka/home/11.04/chess.css
Tanivetka/home/11.04/chess.html

домашка 11.04 шахматная доска градиент

---

Tanivetka/home/09.09/form.html

домашка 09.04 форма

---

Tanivetka/work/14.04/chessboard.css
Tanivetka/work/14.04/chessboard.html

рабочка 14.04 доска с обтеканием

---

fotenya/home/16.04/chess.css
fotenya/home/16.04/index.html

home chessTable

---

yuliya1/work/18.04/childs/index.html
yuliya1/work/18.04/childs/style.css
yuliya1/work/18.04/selectors/index.html
yuliya1/work/18.04/selectors/style.css

@antonkulakov-it Please review

Work 18.04 yuliya

---

sotickmars/work/childs/childs.css
sotickmars/work/childs/index.html
sotickmars/work/selectors/index.html
sotickmars/work/selectors/selectors.css

Ilya work 18.04

---

dmitrylunkov/work/18.04/selectors/index.html
dmitrylunkov/work/18.04/selectors/main.css

Class work 18.04 selectors

---

ekaterinazhuk/home/18.04/chessFloat/index.html
ekaterinazhuk/home/18.04/chessFloat/main.css

1boardFloat

---

fotenya/home/18.04/chess.css
fotenya/home/18.04/chessT.css
fotenya/home/18.04/index.html
fotenya/home/18.04/index1.html
fotenya/home/19.04/chess.css
fotenya/home/19.04/chessT.css
fotenya/home/19.04/index.html
fotenya/home/19.04/indexT.html

Fotenya home 19.04

---

oxana1510/work/20.04/index.html
oxana1510/work/20.04/index2.html
oxana1510/work/20.04/style1.css
oxana1510/work/20.04/style2.css

20.04 work

---

Marat/work/20.04/main.css

work 20.04

---

dmitrylunkov/work/18.04/selectors/main.css

Dmitrylunkovwork18.04

---

yuliya1/work/20.04/index.html
yuliya1/work/20.04/style.css
yuliya1/work/20.04/style2.css

@antonkulakov-it Please review

Yuliya-work-20.04

---

vladdd/work/20.04/index.html
vladdd/work/20.04/mycss.css

vlad work 20.04

---

sotickmars/work/20.04/chet.css
sotickmars/work/20.04/index.html
sotickmars/work/20.04/position.css

ПОДСЧЕТ 20.04

---

dmitrylunkov/home/22.04/Task1Formulas/index.html
dmitrylunkov/home/22.04/Task2Squares/index.html
dmitrylunkov/home/22.04/Task2Squares/styles.css
dmitrylunkov/home/22.04/Task3Pagination/index.html
dmitrylunkov/home/22.04/Task3Pagination/styles.css
dmitrylunkov/home/22.04/Task4Icon/index.html
dmitrylunkov/home/22.04/Task4Icon/style.css
dmitrylunkov/home/22.04/Task5Calendar/index.html
dmitrylunkov/home/22.04/Task5Calendar/main.css
dmitrylunkov/home/22.04/Task6Numbers/index.html
dmitrylunkov/home/22.04/Task6Numbers/main.css

Home work 22.04 6 tasks

---

fotenya/home/20.04/indexA.html
fotenya/home/20.04/indexB.html
fotenya/home/20.04/indexC.html
fotenya/home/20.04/indexD.html
fotenya/home/20.04/indexE.html
fotenya/home/20.04/mainA.css
fotenya/home/20.04/mainB.css
fotenya/home/20.04/mainC.css
fotenya/home/20.04/mainD.css
fotenya/home/20.04/mainE.css

four home task

---

medrom4/home/20-22.04/archive/archive.html
medrom4/home/20-22.04/archive/archivestyle.css
medrom4/home/20-22.04/board/board.html
medrom4/home/20-22.04/board/boardstyle.css
medrom4/home/20-22.04/fivesquares/fivesquares.css
medrom4/home/20-22.04/fivesquares/fivesquares.html
medrom4/home/20-22.04/formyli/formyli.html
medrom4/home/20-22.04/listoften/list.css
medrom4/home/20-22.04/listoften/list.html
medrom4/home/20-22.04/smile/smalestyle.css
medrom4/home/20-22.04/smile/smile.html

home-20-22.04

---

oxana1510/home/20.04/index1.html
oxana1510/home/20.04/index2.html
oxana1510/home/20.04/index3.html
oxana1510/home/20.04/index4.html
oxana1510/home/20.04/index5.html
oxana1510/home/20.04/index6.html
oxana1510/home/20.04/style2.css
oxana1510/home/20.04/style3.css
oxana1510/home/20.04/style4.css
oxana1510/home/20.04/style5.css
oxana1510/home/20.04/style6.css
oxana1510/work/20.04/index.html
oxana1510/work/20.04/index2.html
oxana1510/work/20.04/style1.css
oxana1510/work/20.04/style2.css

Oxana1510 home 20.04

---

hannashyshko/home/20.04/index1.html
hannashyshko/home/20.04/index2.html
hannashyshko/home/20.04/index3.html
hannashyshko/home/20.04/index4.html
hannashyshko/home/20.04/index5.html
hannashyshko/home/20.04/styles.css
hannashyshko/home/20.04/styles2.css
hannashyshko/home/20.04/styles3.css
hannashyshko/home/20.04/styles4.css
hannashyshko/home/20.04/styles5.css

half completed

---

Tanivetka/home/20.04/image1.html

домашка 20.04 картинка №1

---

Tanivetka/home/20.04/image2.css
Tanivetka/home/20.04/image2.html

домашка 20.04 изображение №2

---

Marat/home/20.04/calendar.css
Marat/home/20.04/calendar.html
Marat/home/20.04/digits.css
Marat/home/20.04/digits.html
Marat/home/20.04/index.html
Marat/home/20.04/indexone.html
Marat/home/20.04/indextwo.html
Marat/home/20.04/main.css
Marat/home/20.04/mainone.css
Marat/home/20.04/smile.css
Marat/home/20.04/smile.html

Home-20.04

---

dima1745/home/20.04/1/index.html
dima1745/home/20.04/2/index.css
dima1745/home/20.04/2/index.html
dima1745/work/20.04/index.html
dima1745/work/20.04/position.css
dima1745/work/20.04/position_second.css

Задания ,которые осилил(

---

Tanivetka/home/20.04/image3.css
Tanivetka/home/20.04/image3.html

Домашка 20.04 изображение №3

---

dmitrylunkov/work/23.04/index.html
dmitrylunkov/work/23.04/style.css

Dmitrylunkovwork23.04

---

yuliya1/work/23.04/index.html
yuliya1/work/23.04/style.css

@antonkulakov-it Please review

Yuliya_work_23.04

---

gatok/work/25.04/index.css
gatok/work/25.04/index.html

work_25.04

---

vladdd/work/23.04/index23-04.html
vladdd/work/23.04/mycss.css

Vlad-Work-23.04

---

Tanivetka/work/23.04/table.css
Tanivetka/work/23.04/table.html
Tanivetka/work/23.04/test.html

рабочка 23.04 таблица

---

sotickmars/work/23.04/table.css
sotickmars/work/23.04/table.html

ClassWork 23.04

---

fotenya/home/23.04/indexB.html
fotenya/home/23.04/indexC.css
fotenya/home/23.04/indexC.html
fotenya/home/23.04/mainB.css

home maket layout

---

medrom4/work/23.04/html.html
medrom4/work/23.04/htmlstyle.css

work-23.04-site

---

dmitrylunkov/work/25.04/index.html
dmitrylunkov/work/25.04/style.css

Class work 25.04 radio buttons labels

---

fotenya/work/27.04/index.html
fotenya/work/27.04/main.css

class work

---

Tanivetka/work/27.04/slider.css
Tanivetka/work/27.04/slider.html

рабочка 27.04 слайдер

---

Tanivetka/home/25.04/index.css
Tanivetka/home/25.04/index.html

домашка 25.04 переключатель цифр

---

sotickmars/work/27.04/index.html
sotickmars/work/27.04/slaid.css

classwork 27.04

---

vladdd/work/27.04/index.html
vladdd/work/27.04/mycss.css

vlad work 27.04

---

fotenya/home/28.04/index.html
fotenya/home/28.04/main.css
fotenya/work/27.04/index.html
fotenya/work/27.04/main.css

Fotenya home 28.04

---

Tanivetka/home/27.04/chess_anim.css
Tanivetka/home/27.04/chess_anim.html

домашка 27.04 фигуры с анимацией

---

fotenya/work/2.05/index.html
fotenya/work/2.05/main.css

class work2.05

---

ebces/home/02.05/css.css
ebces/home/02.05/index.html

onetwothree

---

vladdd/work/04.05/index.html
vladdd/work/04.05/mycss.css

vlad-work 04.05

---

oxana1510/work/04.05/index.html
oxana1510/work/04.05/style.css

04.05 work

---

yuliya1/work/04.05/index.html
yuliya1/work/04.05/style1.css

Yuliya_work_04.05_block

---

medrom4/work/4.05/html.html
medrom4/work/4.05/style.css

five-blocks-adaptation

---

sotickmars/work/04.05/5div.css
sotickmars/work/04.05/index.html

Classwork 04.05

---

fotenya/work/4.05/index.html
fotenya/work/4.05/main.css

classwork 4.05

---

dmitrylunkov/work/04.05/index.html
dmitrylunkov/work/04.05/style.css

Class work 04.05 page layout with breakpoints

---

dmitrylunkov/home/06.05/index.html
dmitrylunkov/home/06.05/styles.css

Home work 06.05 animated ball

---

sotickmars/home/25.04/div.css
sotickmars/home/25.04/index2.html

homework 25.04 исправление косяка

---

oxana1510/home/04.05/index.html
oxana1510/home/04.05/style.css

04.05 home

---

medrom4/home/4.05/ballon.html
medrom4/home/4.05/style.css

bouncing-ball

---

sotickmars/home/04.05/animation.css
sotickmars/home/04.05/index.html

home 04.05 МЯЧ

---

fotenya/home/6.05/index.html
fotenya/home/6.05/main.css
fotenya/home/9.05/index.html
fotenya/home/9.05/main.css
fotenya/work/7.05/index.html
fotenya/work/7.05/main.css

@antonkulakov-it  please review

Fotenya home 9.05

---

fotenya/home/6.05/index.html
fotenya/home/6.05/main.css
fotenya/work/4.05/index.html
fotenya/work/4.05/main.css

Fotenya home 6.05

---

fotenya/home/6.05/index.html
fotenya/home/6.05/main.css
fotenya/work/7.05/index.html
fotenya/work/7.05/main.css

Fotenya work 7.05

---

medrom4/work/18.05_J_S/html.html
medrom4/work/18.05_J_S/script.js

work-JS-18.05

---

hannashyshko/home/19.05/index.html
hannashyshko/home/19.05/main.js

if\else if

---

oxana1510/home/21.05/index.html
oxana1510/home/21.05/script.js

21.05 home

---

medrom4/work/21.05/index.html
medrom4/work/21.05/script.js

PesniSozvezdiiGonhixPsov

---

dmitrylunkov/home/20.05/index.html
dmitrylunkov/home/20.05/script.js
dmitrylunkov/home/20.05/style.css

Home work 20.05 JS Person Age

---

dmitrylunkov/home/25.05/index.html
dmitrylunkov/home/25.05/script.js

Home work 25.05 palindrom string

---

hannashyshko/home/24.05/index.html
hannashyshko/home/24.05/main.js

palindrome

---

yuliya1/home/21.05/index.html
yuliya1/home/21.05/script.js

@antonkulakov-it  please review

Yuliya_home_21.05

---

yuliya1/work/21.05/index.html
yuliya1/work/21.05/script.js

work-generator

---

knightjuly/home/21.05/index.html

home-21.05

---

dmitrylunkov/home/23.05/index.html
dmitrylunkov/home/23.05/script.js
dmitrylunkov/home/23.05/style.css

Homework 23.05 switch construction

---

ekaterinazhuk/home/JS_20_05/index.html
ekaterinazhuk/home/JS_20_05/script.js

please review 
@antonkulakov-it

homeWorkJS-20.05
